### ISSUE TITLE
Saving doesn't work

### ISSUE THREAD

**Issue by pealco** [earle/django-bootstrap#13]
It seems that instances of classes subclassed from BootstrapForm don't have a save method. As a result, it's not possible to save those forms.

**Comment by earle** [comment]
I believe only ModelForms have a .save() method.  There's a previous thread on creating a BoostrapModelForm, but I havent had time to get around to doing it.

**Comment by pealco** [comment]
Ah, you're right. I've been using ModelForms for so long that I forgot how regular Forms worked.

Am I missing something similar when I find that there's no cleaned_data attribute?

**Comment by earle** [comment]
Until the form validation is attempted, there is no cleaned_data attribute.  Use:

if form.is_valid():
     val = form.cleaned_data[key]
