### ISSUE TITLE
Fieldset

### ISSUE THREAD

**Issue by nashrafeeg** [earle/django-bootstrap#15]
class Meta:
        layout = (
            Fieldset("Please Login", "username", "password", ),
        )
when i try to add a Fieldset as in the readme i get an error 'name 'Fieldset' is not defined' i am sure i am doing some noob mistake and not importing some thing but i am not sure what and google does not seem to have any results on why it does not work

**Comment by earle** [comment]
You're not importing the Fieldset from bootstrap/forms.py

**Comment by nashrafeeg** [comment]
thanks that fixed it.
