### ISSUE TITLE
Django-bootstrap working with SessionWizardView (dev)

### ISSUE THREAD

**Issue by youpsla** [earle/django-bootstrap#16]
Hello,
I've try django-bootstrap working with SessionWizardView and my first step form is empty. Not really empty because the hidden field `<input type="hidden" name="inscription_wizard-current_step" value="0" id="id_inscription_wizard-current_step" />` is in the html source of the rendered page.

But others fields are not. I'm not enough django proof to find a solution but of course I agree testing.

It would be really great I think if the both can work together.

here is my code:

forms.py
```from bootstrap.forms import BootstrapForm, Fieldset

class Step1Form(BootstrapForm):

``````
class Meta:
    layout = (
        Fieldset("Please Login", "email_adresse", "telephone", ),
    )

email_adresse = forms.EmailField(max_length=255)
telephone = FRPhoneNumberField(required=False)```
``````

views.py
```class InscriptionWizard(SessionWizardView):

``````
def get_template_names(self):
    return 'clients/session_wizard.html'```
``````

and html:

```
<form action="." method="post">{% csrf_token %}

    {{ wizard.management_form }}

    {% if wizard.form.forms %}
        {{ wizard.form.management_form }}
        {% for form in wizard.form.forms %}
            {{ form }}
        {% endfor %}
    {% else %}
        {{ form }}
    {% endif %}

    <input type="submit">
</form>
{% endblock %}
```

If you have any idea ... let me jnow.

Best regards an thanks a lots for the job.

Alain

**Comment by earle** [comment]
Hidden fields are fixed
