### ISSUE TITLE
Compatability with ModelForms?

### ISSUE THREAD

**Issue by victorhooi** [earle/django-bootstrap#24]
Hi,

I was curious whether you had any plans for compatibility with Django ModelForms?

E.g. I'm using the new class-based CreateView, and I'm not sure how I would go about hooking django-boostrap into my forms?

Cheers,
Victor

**Comment by rotaris** [comment]
I think integration with ModelForms was added when issue #3 was resolved.

**Comment by earle** [comment]
Correct.  This is compatible with ModelForms
