### ISSUE TITLE
Adding templatetags support?

### ISSUE THREAD

**Issue by fengsi** [earle/django-bootstrap#26]
I've been using django-uni-form in the past. It can be used both in forms.py and as templatetag in a template.

The reason for templatetags support is simple: it's easy to write your own forms based on BootstrapForm/BootstrapModalForm/etc, however when you are using 3rd-party apps, replacing ALL forms.Form with BootstrapForm in source files would not be a good idea.

Actually there is another Django app which provides a simple templatetag "as_bootstrap" to convert Django standard form output to bootstrap style:
https://github.com/dyve/django-bootstrap-toolkit

It worked well until bootstrap upgraded to 2.0.0. It doesn't have fieldset support though (due to the nature of templatetags).

Both methods have their own advantage: in forms you have more control (like fieldset support, which is also provided in django-uni-form), and in templatetag you can simply convert standard forms used by 3rd-party apps to bootstrap style.

So I was wondering if you can add templatetags support in django-bootstrap? Probably a similar "as_bootstrap" templatetag.

Thanks.

**Comment by earle** [comment]
I see the need for your use case -- although a templatetag will work, it definitely isnt the most ideal situation -- and as you mentioned, there will be significant features lost, including the one you mentioned.

You do realize you could simply override the Form input in your third party app in one place, and get away with everything as is....?

**Comment by fengsi** [comment]
Could you please explain "override the Form input"? What I want is avoiding touching any forms.py/views.py/urls.py of a 3rd-party app. Thanks.

**Comment by goodrichj** [comment]
Please do explain! I don't see how, for example, I would override the django.contrib.auth forms in a nice way.

It seems to me that adding a template tag that instantiates the form using the mixin should work. I don't see anywhere else that makes sense to do this override.

Please re-open the issue!
