### ISSUE TITLE
Change name to something more explicit

### ISSUE THREAD

**Issue by pydanny** [earle/django-bootstrap#28]
Just a suggestion but django-bootstrap could mean:
- A bootstrap Django project
- A set of templates for Twitter bootstrap
- A form library for twitter bootstrap :)

Perhaps something like django-bootstrap-forms?

**Comment by jterrace** [comment]
I think this can be closed as duplicate of #38

**Comment by pthrasher** [comment]
Closing as duplicate. Let's move the discussion over to the above referenced issue.
