### ISSUE TITLE
Adding alert classes to non_field_errors

### ISSUE THREAD

**Issue by davidbgk** [earle/django-bootstrap#31]
Hello,

I propose to add `alert alert-error` to the `error_list` method:
https://github.com/earle/django-bootstrap/blob/master/bootstrap/forms.py#L13

This way non_field_errors will be on a red background, consistent with fields' related errors.

**Comment by earle** [comment]
Sounds good, want to submit a pull request?

**Comment by davidbgk** [comment]
OK, I'll do that ASAP :)

**Comment by earle** [comment]
Were you still working on this?

**Comment by davidbgk** [comment]
Sorry, I totally forgot. Pull request sent.

**Comment by jterrace** [comment]
This looks like it's fixed on master, so I think this can be closed. #31 could also be closed.
