### ISSUE TITLE
Missing support for non_field_error errors.

### ISSUE THREAD

**Issue by ashchristopher** [earle/django-bootstrap#33]
If I were to raise forms.ValidationError("Error goes here"), it will be missing from your form rendering if using the as_div() method.

**Comment by marltu** [comment]
#31 is similar issue I think.

**Comment by ashchristopher** [comment]
It is similar, but it looks like the form's as_div() just isn't rendering enough of the form. If I have a chance, ill try to submit a patch.

**Comment by jterrace** [comment]
This is fixed in master - I think you can close this.
