### ISSUE TITLE
Incorrect / misleading / already-taken name in setup.py

### ISSUE THREAD

**Issue by doismellburning** [earle/django-bootstrap#38]
In setup.py, name is set to 'bootstrap'

Alas that name is taken in pypi: http://pypi.python.org/pypi/bootstrap

@earle - could you please pick another name, and perhaps deploy to pypi? (Given the choice, I'd much rather require a 0.1 from pypi than a Github HEAD...)

**Comment by jterrace** [comment]
I'd like to submit a pull request for this if possible. Ping @earle - what's the best approach here? I'd say rename the module from bootstrap to django-bootstrap, but it wouldn't be backwards compatible.

**Comment by earle** [comment]
This seems like a very reasonable approach to me!  Submit away!

**Comment by jterrace** [comment]
Looks like django-bootstrap is taken too >.<
http://pypi.python.org/pypi/django-bootstrap

djbootstrap is _also_ taken:
http://pypi.python.org/pypi/djbootstrap

I'm thinking maybe django-bootstrap-forms or django-twitter-bootstrap?

**Comment by jterrace** [comment]
What do you think of `django-bootstrap-forms`? I can submit a pull request for it if you'll upload it to pypi with that name.

**Comment by pthrasher** [comment]
django-bootstrap-forms is available.

@earle what do you think of that?

App name could be bootstrapforms.

That said, bootstrapforms and bootstrap-forms are also available.

**Comment by jterrace** [comment]
I don't think the app name has to change. The pypi name can be `django-bootstrap-forms` while the app name is still `bootstrap`. This will keep everything backwards compatible for existing users.

**Comment by pthrasher** [comment]
I believe there's an app name conflict as well. Though, I'm not sure if that's another django app with duplicate functionality, or if it does something different. If it does something different, someone might like to include both in their project. If that's the case, we don't want to exclude those users. That said, it may not really be an issue.

Also... does the name _need_ to be so long and explicit? There are plenty of django apps out there without django in the name on pypi. South for instance.

**Comment by jterrace** [comment]
Doesn't really matter to me what the name ends up being, just as long as it's on pypi, which makes it a little easier to include in a requirements file.
