### ISSUE TITLE
Fieldset Close Tag

### ISSUE THREAD

**Issue by jterrace** [earle/django-bootstrap#39]
Fieldsets are being closed at the wrong place. This is what I'm seeing generated:

```
<form ...>
        <fieldset><legend>Details</legend></fieldset>
        <div class="control-group">...</div>
</form>
```

Bootstrap documentation shows examples with this format instead:

```
<form ...>
        <fieldset>
        <legend>Details</legend>
        <div class="control-group">...</div>
        </fieldset>
</form>
```

This is causing some weird spacing issues with Bootstrap 2.0.1 and django-bootstrap from the latest master.

**Comment by pthrasher** [comment]
This appears to be corrected. Not sure when it was fixed, but I'm closing this issue.
