### ISSUE TITLE
i can not render this style(<label class="radio inline">)

### ISSUE THREAD

**Issue by jiangzhx** [earle/django-bootstrap#51]
<div class="control-group ">
            <label class="control-label" for="input01"><h5>app platform：</h5></label>
            <div class="controls ">
              <label class="radio inline">
              <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" checked="">
               Android </label>
              <label class="radio inline">
              <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">
               iOS  </label>
            </div>

```
      </div>
```

**Comment by pthrasher** [comment]
While this is currently fully 2.0 compatible, it's missing a few features.
